### ISSUE TITLE
(No issue) Just saying Thanks

### ISSUE THREAD

**Issue by alphafox02** [steeviebops/jhacktv-gui#1]
Exactly the type of GUI I’ve been looking for. Works perfectly with HackTV. Also a great example that could maybe be adapted to other command line tools. Thanks for spending the time to make and share.

**Comment by steeviebops** [comment]
Thanks for the feedback! I originally planned to just make this for my own use so it's great to hear that others are finding this useful too.

**Comment by alphafox02** [comment]
Haven’t checked this in awhile, glad I did just now. I’ll update and include it in the latest DragonOS ISO. Also meant to ask, would you perhaps have any interest or time in making a GUI similar to this but for other programs - like grgsm for example?

**Comment by steeviebops** [comment]
This year will be a busy one with personal commitments, so I may not have the time unfortunately.
